export const citiesList = [
  { city: "Cairo", governorate: "Cairo" },
  { city: "Alexandria", governorate: "Alexandria" },
  { city: "Giza", governorate: "Giza" },
  { city: "Shubra El-Kheima", governorate: "Qalyubia" },
  { city: "Port Said", governorate: "Port Said" },
  { city: "Suez", governorate: "Suez" },
  { city: "El-Mahalla El-Kubra", governorate: "Gharbia" },
  { city: "Luxor", governorate: "Luxor" },
  { city: "Mansoura", governorate: "Dakahlia" },
  { city: "Tanta", governorate: "Gharbia" },
  { city: "Asyut", governorate: "Asyut" },
  { city: "Ismailia", governorate: "Ismailia" },
  { city: "Faiyum", governorate: "Faiyum" },
  { city: "Zagazig", governorate: "Sharqia" },
  { city: "Damietta", governorate: "Damietta" },
  { city: "Aswan", governorate: "Aswan" },
  { city: "Minya", governorate: "Minya" },
  { city: "Damanhur", governorate: "Beheira" },
  { city: "Beni Suef", governorate: "Beni Suef" },
  { city: "Qena", governorate: "Qena" },
  { city: "Sohag", governorate: "Sohag" },
  { city: "Hurghada", governorate: "Red Sea" },
  { city: "6th of October", governorate: "Giza" },
  { city: "Shibin El Kom", governorate: "Monufia" },
  { city: "Banha", governorate: "Qalyubia" },
  { city: "Arish", governorate: "North Sinai" },
  { city: "Mallawi", governorate: "Minya" },
  { city: "Bilqas", governorate: "Dakahlia" },
  { city: "Kafr El-Sheikh", governorate: "Kafr El-Sheikh" },
  { city: "Marsa Matruh", governorate: "Matrouh" },
  { city: "Beni Mazar", governorate: "Minya" },
  { city: "Al-Kharijah", governorate: "New Valley" },
  { city: "Qus", governorate: "Qena" },
  { city: "Sallum", governorate: "Matrouh" },
  { city: "Edku", governorate: "Beheira" },
  { city: "Al-Hamra", governorate: "Matrouh" },
  { city: "Marsa Alam", governorate: "Red Sea" },
  { city: "Safaga", governorate: "Red Sea" },
  { city: "Bardawil", governorate: "North Sinai" },
  { city: "Rafah", governorate: "North Sinai" },
  { city: "Belbeis", governorate: "Sharqia" },
  { city: "Helwan", governorate: "Cairo" },
  { city: "Damietta Port", governorate: "Damietta" },
  { city: "Al-Badari", governorate: "Asyut" },
  { city: "Al-Ayyat", governorate: "Giza" },
  { city: "Abu Simbel", governorate: "Aswan" },
  { city: "Al-Fashn", governorate: "Beni Suef" },
  { city: "Al-Kharga", governorate: "New Valley" },
  { city: "Al-Kawamil", governorate: "Sohag" },
  { city: "Al-Minya", governorate: "Minya" },
  { city: "Al-Qusayr", governorate: "Red Sea" },
  { city: "Al-Rawda", governorate: "North Sinai" },
  { city: "Al-Wasta", governorate: "Beni Suef" },
  { city: "Almazah", governorate: "Cairo" },
  { city: "Al-Qanayat", governorate: "Sharqia" },
  { city: "Al-Aziziyah", governorate: "Sharqia" },
  { city: "Abu Kabir", governorate: "Sharqia" },
  { city: "Abu Hummus", governorate: "Beheira" },
  { city: "Abu Tesht", governorate: "Qena" },
  { city: "Akhmim", governorate: "Sohag" },
  { city: "Atfih", governorate: "Giza" },
  { city: "Baltim", governorate: "Kafr El-Sheikh" },
  { city: "Basyun", governorate: "Gharbia" },
  { city: "Biba", governorate: "Beni Suef" },
  { city: "Borg El-Arab", governorate: "Alexandria" },
  { city: "Dairut", governorate: "Asyut" },
  { city: "Dar El-Salam", governorate: "Sohag" },
  { city: "Deir Mawas", governorate: "Minya" },
  { city: "Desouk", governorate: "Kafr El-Sheikh" },
  { city: "Dishna", governorate: "Qena" },
  { city: "El-Badrashein", governorate: "Giza" },
  { city: "El-Ballana", governorate: "Aswan" },
  { city: "El-Dabaa", governorate: "Matrouh" },
  { city: "El-Dakhla", governorate: "New Valley" },
  { city: "El-Delengat", governorate: "Beheira" },
  { city: "El-Hawamdeya", governorate: "Giza" },
  { city: "El-Idwa", governorate: "Minya" },
  { city: "El-Maasara", governorate: "Cairo" },
  { city: "El-Qanater El-Khayreya", governorate: "Qalyubia" },
  { city: "El-Qantara", governorate: "Ismailia" },
  { city: "El-Quseir", governorate: "Red Sea" },
  { city: "Faraskur", governorate: "Damietta" },
  { city: "Fayed", governorate: "Ismailia" },
  { city: "Fuwah", governorate: "Kafr El-Sheikh" },
  { city: "Girga", governorate: "Sohag" },
  { city: "Hawamdiyah", governorate: "Giza" },
  { city: "Ihnasiya", governorate: "Beni Suef" },
  { city: "Isna", governorate: "Luxor" },
  { city: "Kafr El-Batikh", governorate: "Damietta" },
  { city: "Kafr El-Dawwar", governorate: "Beheira" },
  { city: "Kafr El-Zayat", governorate: "Gharbia" },
  { city: "Kom Ombo", governorate: "Aswan" },
  { city: "Madinat Sittah Uktubar", governorate: "Giza" },
  { city: "Manfalut", governorate: "Asyut" },
  { city: "Manqabad", governorate: "Asyut" },
  { city: "Matay", governorate: "Minya" },
  { city: "Minyat an Nasr", governorate: "Dakahlia" },
  { city: "Mit Abu Ghaleb", governorate: "Giza" },
  { city: "Mit Abu al-Kum", governorate: "Monufia" },
  { city: "Mit Ghamr", governorate: "Dakahlia" },
  { city: "Mit Salsil", governorate: "Dakahlia" },
  { city: "Miyah", governorate: "Sharqia" },
  { city: "Nag Hammadi", governorate: "Qena" },
  { city: "Nabq", governorate: "South Sinai" },
  { city: "New Damietta", governorate: "Damietta" },
  { city: "New Salhia", governorate: "Sharqia" },
  { city: "New Tiba", governorate: "Luxor" },
  { city: "Oseem", governorate: "Giza" },
  { city: "Qaha", governorate: "Qalyubia" },
  { city: "Qalyub", governorate: "Qalyubia" },
  { city: "Qiman al-Arus", governorate: "Beni Suef" },
  { city: "Ras Gharib", governorate: "Red Sea" },
  { city: "Ras Sedr", governorate: "South Sinai" },
  { city: "Safaga", governorate: "Red Sea" },
  { city: "Saint Catherine", governorate: "South Sinai" },
  { city: "Samalut", governorate: "Minya" },
  { city: "Samannoud", governorate: "Gharbia" },
  { city: "Senbellawein", governorate: "Dakahlia" },
  { city: "Shebin El Qanater", governorate: "Qalyubia" },
  { city: "Sharm El-Sheikh", governorate: "South Sinai" },
  { city: "Sheikh Zuweid", governorate: "North Sinai" },
  { city: "Shubra El Kheima", governorate: "Qalyubia" },
  { city: "Siwa", governorate: "Matrouh" },
  { city: "Sohag", governorate: "Sohag" },
  { city: "Sumusta al Waqf", governorate: "Beni Suef" },
  { city: "Tahta", governorate: "Sohag" },
  { city: "Talkha", governorate: "Dakahlia" },
  { city: "Tamiya", governorate: "Faiyum" },
  { city: "Toukh", governorate: "Qalyubia" },
  { city: "Wadi El-Natrun", governorate: "Beheira" },
  { city: "Zefta", governorate: "Gharbia" },
  { city: "Kawm Hamadah", governorate: "Beheira" },
  { city: "El-Zarqa", governorate: "Damietta" },
  { city: "Az Zarqa", governorate: "Damietta" },
  { city: "Hihya", governorate: "Sharqia" },
  { city: "Kafr Saqr", governorate: "Sharqia" },
  { city: "Minya El-Qamh", governorate: "Sharqia" },
  { city: "Awlad Saqr", governorate: "Sharqia" },
  { city: "Kafr Shukr", governorate: "Qalyubia" },
  { city: "El-Atf", governorate: "Monufia" },
  { city: "Sadat City", governorate: "Monufia" },
  { city: "Menouf", governorate: "Monufia" },
  { city: "Quweisna", governorate: "Monufia" },
  { city: "Bagour", governorate: "Monufia" },
  { city: "Shibin El Kom", governorate: "Monufia" },
  { city: "Ashmoun", governorate: "Monufia" },
  { city: "Birket El Sab", governorate: "Monufia" },
  { city: "Helwan", governorate: "Cairo" },
  { city: "El-Mahalla El-Kubra", governorate: "Gharbia" },
  { city: "Samanoud", governorate: "Gharbia" },
  { city: "Kafr El-Zayat", governorate: "Gharbia" },
  { city: "Basyoun", governorate: "Gharbia" },
  { city: "Qutour", governorate: "Gharbia" },
  { city: "Tanta", governorate: "Gharbia" },
  { city: "Zefta", governorate: "Gharbia" },
  { city: "Banha", governorate: "Qalyubia" },
  { city: "Qalyub", governorate: "Qalyubia" },
  { city: "Shebin El Qanater", governorate: "Qalyubia" },
  { city: "Toukh", governorate: "Qalyubia" },
  { city: "Qaha", governorate: "Qalyubia" },
  { city: "El-Khanka", governorate: "Qalyubia" },
  { city: "Kafr Shukr", governorate: "Qalyubia" },
  { city: "Obour", governorate: "Qalyubia" },
  { city: "Al-Shorouk", governorate: "Cairo" },
  { city: "Al-Salam", governorate: "Cairo" },
  { city: "New Cairo", governorate: "Cairo" },
  { city: "Badr", governorate: "Cairo" },
  { city: "15th of May", governorate: "Cairo" },
  { city: "Madinet Nasr", governorate: "Cairo" },
  { city: "Al Rehab", governorate: "Cairo" },
  { city: "Giza", governorate: "Giza" },
  { city: "October Gardens", governorate: "Giza" },
  { city: "Hadayeq El-Ahram", governorate: "Giza" },
  { city: "Al-Ayyat", governorate: "Giza" },
  { city: "Al-Saff", governorate: "Giza" },
  { city: "Al-Badrashein", governorate: "Giza" },
  { city: "Bulaq El Dakrour", governorate: "Giza" },
  { city: "Kerdasa", governorate: "Giza" },
  { city: "Sheikh Zayed", governorate: "Giza" },
  { city: "Imbaba", governorate: "Giza" },
  { city: "El-Haram", governorate: "Giza" },
  { city: "Faisal", governorate: "Giza" },
  { city: "El-Maryoutia", governorate: "Giza" },
  { city: "Warraq", governorate: "Giza" },
  { city: "Dahshur", governorate: "Giza" },
  { city: "Sphinx", governorate: "Giza" },
  { city: "Shubra", governorate: "Cairo" },
  { city: "Ain Shams", governorate: "Cairo" },
  { city: "Al-Marg", governorate: "Cairo" },
  { city: "Matareya", governorate: "Cairo" },
  { city: "El-Gomhoureya", governorate: "Cairo" },
  { city: "Hadayek El-Kobba", governorate: "Cairo" },
  { city: "Kobri El-Qobba", governorate: "Cairo" },
  { city: "Abbassia", governorate: "Cairo" },
  { city: "Zamalek", governorate: "Cairo" },
  { city: "Dokki", governorate: "Giza" },
  { city: "Agouza", governorate: "Giza" },
  { city: "Mohandessin", governorate: "Giza" },
  { city: "Manial", governorate: "Cairo" },
  { city: "Sayeda Zeinab", governorate: "Cairo" },
  { city: "Dar El-Salam", governorate: "Cairo" },
  { city: "Bulaq", governorate: "Cairo" },
  { city: "Zawyet El-Nahyan", governorate: "Cairo" },
  { city: "Qasr El-Nil", governorate: "Cairo" },
  { city: "Garden City", governorate: "Cairo" },
  { city: "El-Mokattam", governorate: "Cairo" },
  { city: "El-Zaher", governorate: "Cairo" },
  { city: "Manshiyat Naser", governorate: "Cairo" },
  { city: "El-Sayeda Aisha", governorate: "Cairo" },
  { city: "Bab El-Louk", governorate: "Cairo" },
  { city: "Beyt El-Watan", governorate: "Cairo" },
  { city: "El-Tagamu El-Khamis", governorate: "Cairo" },
  { city: "Madinet Nasr", governorate: "Cairo" },
  { city: "Nasr City", governorate: "Cairo" },
  { city: "El-Matariya", governorate: "Cairo" },
  { city: "Rod El-Farag", governorate: "Cairo" },
  { city: "Waili", governorate: "Cairo" },
  { city: "Bab El-Shaariya", governorate: "Cairo" },
  { city: "Sayeda Aisha", governorate: "Cairo" },
  { city: "Darb El-Ahmar", governorate: "Cairo" },
  { city: "El-Khalifa", governorate: "Cairo" },
  { city: "El-Sayeda Zeinab", governorate: "Cairo" },
  { city: "Attaba", governorate: "Cairo" },
  { city: "Kerdasa", governorate: "Giza" },
  { city: "Beit El Watan", governorate: "Cairo" },
  { city: "Fustat", governorate: "Cairo" },
];
